apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "redis-access"
spec:
  description: "L3-L4 policy on redis server"
  endpointSelector:
    matchLabels:
      app: redis
  ingress:
  - fromEndpoints:
    - matchLabels:
        app: sample
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      - port: "9000"
        protocol: TCP
      - port: "5201"
      rules: 
        http: 
        - method: "POST"
          path: "/"
  