# kubectl exec <pod name> -- curl -d "message=hi" redis-service.default.svc.cluster.local:8000

apiVersion: v1 
kind: Pod
metadata:
  name: customer 
  labels:
    org: empire
    class: tiefighter
    app.kubernetes.io/name: tiefighter
spec:
  containers:
  - name: spaceship
    image: nginx