# kubectl exec <pod name> -- curl -d "message=hi" redis-service.default.svc.cluster.local
# kubectl exec --stdin --tty <pod name> -- /bin/bash

apiVersion: v1 
kind: Pod
metadata:
  name: customer 
  labels:
    app: sample
spec:
  containers:
  - name: customer
    image: nginx