# kubectl exec <pod name> -- curl -d "message=hi" redis-service.default.svc.cluster.local:8000

apiVersion: v1 
kind: Pod
metadata:
  name: customer 
  labels:
    org: sample
    class: customer
spec:
  containers:
  - name: customer
    image: nginx